name: Backend Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: List backend directory contents (diagnóstico)
      run: ls -la ${{ github.workspace }}/backend

    - name: Install dependencies (backend)
      run: npm ci
      working-directory: ${{ github.workspace }}/backend

    - name: Build backend (if applicable)
      run: npm run build --if-present
      working-directory: ${{ github.workspace }}/backend

    - name: Run tests (backend)
      run: npm test
      working-directory: ${{ github.workspace }}/backend
